### ISSUE TITLE
svg files loading issue

### ISSUE THREAD

**Issue by Shun2014** [canfoo/vue2.0-taopiaopiao#16]
```
npm run start

> taopiaopiao-server@0.0.0 start E:\workspace\vue\taopiaopiao\server
> node ./bin/www

services running on port 9090
GET /javascripts/app.f27ee68ddb3ef9c510cd.js 200 5.378 ms - 130244
GET /app 304 4.786 ms - -
GET /javascripts/app.f27ee68ddb3ef9c510cd.js 304 0.929 ms - -
GET /stylesheets/app.012a750207e0e7ec260354a1e81618cc.css 304 1.567 ms - -
GET /javascripts/vendor.6fc7238190796b50b9d8.js 304 0.299 ms - -
GET /javascripts/manifest.320b50c7c0f2c60ccd61.js 304 0.404 ms - -
GET /movie/swiper 304 4.383 ms - -
GET /movie/hot/?city=bj 304 9.007 ms - -
GET /movie/coming/?limit=20&offset=0 304 14.427 ms - -
GET /public/img/hno.5bb3a6e.svg 500 3.549 ms - 1355
Error: Failed to lookup view "error" in views directory "./views"
    at Function.render (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\application.js:580:17)
    at ServerResponse.render (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\response.js:1008:7)
    at E:\workspace\vue\taopiaopiao\server\app.js:65:7
    at Layer.handle_error (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\router\index.js:315:13)
    at E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\router\index.js:335:12)
    at IncomingMessage.next (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\router\index.js:275:10)
    at done (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\response.js:1003:25)
    at Function.render (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\application.js:582:14)
GET /public/img/hok.42539e3.svg 500 3.956 ms - 1355
GET /movie/city 304 11.953 ms - -
Error: Failed to lookup view "error" in views directory "./views"
    at Function.render (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\application.js:580:17)
    at ServerResponse.render (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\response.js:1008:7)
    at E:\workspace\vue\taopiaopiao\server\app.js:65:7
    at Layer.handle_error (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\router\index.js:315:13)
    at E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\router\index.js:335:12)
    at IncomingMessage.next (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\router\index.js:275:10)
    at done (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\response.js:1003:25)
    at Function.render (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\application.js:582:14)
GET /public/img/mno.8a74b01.svg 500 1.763 ms - 1355
Error: Failed to lookup view "error" in views directory "./views"
    at Function.render (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\application.js:580:17)
    at ServerResponse.render (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\response.js:1008:7)
    at E:\workspace\vue\taopiaopiao\server\app.js:65:7
    at Layer.handle_error (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\router\index.js:315:13)
    at E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\router\index.js:335:12)
    at IncomingMessage.next (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\router\index.js:275:10)
    at done (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\response.js:1003:25)
    at Function.render (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\application.js:582:14)
GET /public/img/mok.d9e5301.svg 500 5.900 ms - 1355
Error: Failed to lookup view "error" in views directory "./views"
    at Function.render (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\application.js:580:17)
    at ServerResponse.render (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\response.js:1008:7)
    at E:\workspace\vue\taopiaopiao\server\app.js:65:7
    at Layer.handle_error (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\router\index.js:315:13)
    at E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\router\index.js:335:12)
    at IncomingMessage.next (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\router\index.js:275:10)
    at done (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\response.js:1003:25)
    at Function.render (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\application.js:582:14)
GET /public/img/eno.fb4a488.svg 500 1.040 ms - 1355
Error: Failed to lookup view "error" in views directory "./views"
    at Function.render (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\application.js:580:17)
    at ServerResponse.render (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\response.js:1008:7)
    at E:\workspace\vue\taopiaopiao\server\app.js:65:7
    at Layer.handle_error (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\router\index.js:315:13)
    at E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\router\index.js:335:12)
    at IncomingMessage.next (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\router\index.js:275:10)
    at done (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\response.js:1003:25)
    at Function.render (E:\workspace\vue\taopiaopiao\server\node_modules\express\lib\application.js:582:14)
GET /app 304 1.375 ms - -
GET /img/nostart.0a7b703.svg 304 0.916 ms - -
GET /img/star.ef7d74b.svg 304 2.034 ms - -
GET /img/3dimax.a8f3047.svg 304 3.224 ms - -
GET /img/imax.737a19b.svg 304 3.928 ms - -
GET /img/3d.265e474.svg 304 0.328 ms - -
```

**Comment by Shun2014** [comment]
workaround:
manually remap svg file path in `server/public/javascripts/app.*.js`
e.g.
```
{e.exports=a.p+"../public/img/mno.8a74b01.svg"} => {e.exports=a.p+"/img/mno.8a74b01.svg"}
```
but think it's a better way if we can do that while running `npm run deploy`
